# These are supported funding model platforms

BTC: 1836VfoHMAFmXpXn8Fzp1qWvdtUkTGzT2m

ETH: 0x1e2Eff58047D72E0c9F9F0EA7104014061c5BdAe

DCR: DsjVBZai66cZbWzMBuxz9W2cpLLqPn5uY9x

DOGE: D6UoWSgvS8riA7Nkybjzvt6SY5GNy6yQXH

XRP: rEHdK9WUYxBbqeGrj2R1xpRj9knXzn5B2k

BCH: qzcvhljw0zv5eztpzzcrchk7fzaxru420v55s74gkv
